logging:
    level:
        be.xplore.githubmetrics: ${LOGGING_LEVEL:INFO}
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus", "health" ]
    metrics:
        enable:
            all: true
    health:
        probes:
            enabled: true
spring:
    threads:
        virtual:
            enabled: true
app:
    scheduling:
        enable: true
        workflow_runs_interval: ${APP_SCHEDULING_WORKFLOW_RUNS_INTERVAL:30 */5 * * * ?}
        jobs_interval: ${APP_SCHEDULING_JOBS_INTERVAL:0 */5 * * * ?}
        workflow_run_build_times_interval: ${APP_SCHEDULING_WORKFLOW_RUN_BUILD_TIMES_INTERVAL:10 0 * * * ?}
        pull_requests_interval: ${APP_SCHEDULING_PULL_REQUESTS_INTERVAL:15 0 * * * ?}
        self_hosted_runners_interval: ${SELF_HOSTED_RUNNERS_INTERVAL:20 */5 * * * ?}
        repository_count_interval: ${REPOSITORY_COUNT_INTERVAL:0 0 * * * ?}
    github:
        url: https://api.github.com
        org: "github-insights"
togglz:
    feature-enums: be.xplore.githubmetrics.prometheusexporter.features.Features
    features:
        EXPORTER_JOBS_FEATURE:
            enabled: ${EXPORTER_JOBS_FEATURE:false}
        EXPORTER_WORKFLOW_RUNS_FEATURE:
            enabled: ${EXPORTER_WORKFLOW_RUNS_FEATURE:false}
        EXPORTER_SELF_HOSTED_RUNNERS_EXPORTER:
            enabled: ${EXPORTER_SELF_HOSTED_RUNNERS_EXPORTER:false}
        EXPORTER_REPOSITORIES_FEATURE:
            enabled: ${EXPORTER_REPOSITORIES_FEATURE:false}
        EXPORTER_PULL_REQUESTS_FEATURE:
            enabled: ${EXPORTER_PULL_REQUESTS_FEATURE:false}
