logging:
    level:
        be.xplore.githubmetrics: ${DEBUG_LEVEL:INFO}
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus", "health" ]
    metrics:
        enable:
            all: true
    health:
        probes:
            enabled: true
spring:
    threads:
        virtual:
            enabled: true
app:
    scheduling:
        enable: true
        workflow_runs_interval: ${APP_SCHEDULING_WORKFLOW_RUNS_INTERVAL:30 */1 * * * ?}
        jobs_interval: ${APP_SCHEDULING_JOBS_INTERVAL:0 */1 * * * ?}
        workflow_run_build_times_interval: ${APP_SCHEDULING_WORKFLOW_RUN_BUILD_TIMES_INTERVAL:10 */1 * * * ?}
    github:
        url: https://api.github.com
        org: "github-insights"