logging:
    level:
        be.xplore.githubmetrics: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]
    metrics:
        enable:
            all: true
    health:
        probes:
            enabled: true
spring:
    threads:
        virtual:
            enabled: true
app:
    scheduling:
        enable: true
        workflow_runs_interval: ${APP_SCHEDULING_WORKFLOW_RUNS_INTERVAL:30 */1 * * * ?}
        jobs_interval: ${APP_SCHEDULING_JOBS_INTERVAL:0 */1 * * * ?}
    github:
        url: https://api.github.com
        org: "github-insights"