logging:
    level:
        be.xplore.githubmetrics: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]
    metrics:
        enable:
            all: true
    health:
        probes:
            enabled: true

app:
    github:
        schema: https
        host: "api.github.com"
        org: "github-insights"
