logging:
    level:
        be.xplore.githubmetrics: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]
app.github.host: "https://api.github.com"