logging:
    level:
        be.xplore.githubmetrics: INFO
management:
    endpoints:
        web:
            exposure:
                include: [ "prometheus" ]
    metrics:
        enable:
            all: true
    health:
        probes:
            enabled: true

app:
    scheduling:
        enable: true
    github:
        schema: https
        host: "api.github.com"
        port: 443
        org: "github-insights"