name: Build and Test

on:
    workflow_run:
        workflows: ["Begin Build Workflows Trigger"]
        types:
            -  completed

jobs:
    prepare:

        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            -   name: Cook Chicken
                run: sleep $((RANDOM % 400))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 30 )) -ge 1
                shell: bash
    build:
        needs: prepare
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            -   name: Add Herbs
                run: sleep $((RANDOM % 150))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 30 )) -ge 1
                shell: bash
    test1:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Let Cool
                run: sleep $((RANDOM % 400))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 30 )) -ge 1
                shell: bash
    test2:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Can
                run: sleep $((RANDOM % 300))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 30 )) -ge 1
                shell: bash
