name: Deploy and Publish

on:
    workflow_run:
        workflows: ["Build and Test"]
        types:
            -  completed

jobs:
    get-information:

        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            -   name: Cook Beef
                run: sleep $((RANDOM % 100))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 40 )) -ge 1
                shell: bash
    download-buildfile:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            -   name: Add Herbs
                run: sleep $((RANDOM % 150))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 40 )) -ge 1
                shell: bash
    verify:
        needs: "download-buildfile"
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Let Cool
                run: sleep $((RANDOM % 300))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 40 )) -ge 1
                shell: bash
    publish:
        needs: verify
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Can
                run: sleep $((RANDOM % 300))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 40 )) -ge 1
                shell: bash
