name: Push to Github package registry

on:
    push:
        branches: [ "main" ]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'corretto'

            -   name: Create short Sha
                id: vars
                run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            -   name: Build and Push docker image
                env:
                    SHORT_SHA: ${{ steps.vars.outputs.sha_short }}
                    IMAGE_NAME: "ghcr.io/github-insights/github-metrics"
                    CR_URL: "ghcr.io"
                    CR_USERNAME: ${{ github.actor }}
                    CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
                    BP_OCI_SOURCE: "https://github.com/github-insights/github-metrics"
                run: ./gradlew bootBuildImage