name: Update Documentation

on:
    workflow_run:
        workflows: ["Begin Build Workflows Trigger"]
        types:
            -  completed

jobs:
    prep:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            -   name: Download Tooling
                run: sleep $((RANDOM % 200))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 20 )) -ge 1
                shell: bash

            -   name: Compile Doc Files
                run: sleep $((RANDOM % 200))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 20 )) -ge 1
                shell: bash

            -   name: Upload
                run: sleep $((RANDOM % 200))
                shell: bash
            -   name: Success?
                run: test $((RANDOM % 20 )) -ge 1
                shell: bash
